version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: dev-mysql
    ports:
      - "33306:3306"  # Expose MySQL on host port 33306
    environment:
      MYSQL_ROOT_PASSWORD: devpass
      MYSQL_DATABASE: devdb
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql-data:
